[platformio]
default_envs = esp32c3

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  links2004/WebSockets @ ^2.6.1
  bblanchon/ArduinoJson @ ^7.4.2
  tzapu/WiFiManager @ ^2.0.17
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1

; Una vez instalado por USB, las siguientes actualizaciones pueden hacerse por red:
; upload_protocol = espota
; upload_port = <IP_DEL_ESP32>

[env:esp32c3_ota]
extends = env:esp32c3
upload_protocol = espota
